services: 
  central-server: 
    image: martin2000002/meeting-central-server:latest 
    ports: 
      - "9090:9090" 
    networks: 
      - meeting-network 
    volumes: 
      - ./data:/app/data 
      - ./employees.properties:/app/employees.properties 
 
  alice-white-server: 
    image: martin2000002/meeting-employee-server:latest 
    environment: 
      - EMPLOYEE_NAME=Alice_White 
      - EMPLOYEE_PORT=8081 
    ports: 
      - "8081:8081" 
    networks: 
      - meeting-network 
    depends_on: 
      - central-server 
    volumes: 
      - ./data:/app/data 
      - ./employees.properties:/app/employees.properties 
 
  bob-smith-server: 
    image: martin2000002/meeting-employee-server:latest 
    environment: 
      - EMPLOYEE_NAME=Bob_Smith 
      - EMPLOYEE_PORT=8082 
    ports: 
      - "8082:8082" 
    networks: 
      - meeting-network 
    depends_on: 
      - central-server 
    volumes: 
      - ./data:/app/data 
      - ./employees.properties:/app/employees.properties 
 
  carol-simpson-server: 
    image: martin2000002/meeting-employee-server:latest 
    environment: 
      - EMPLOYEE_NAME=Carol_Simpson 
      - EMPLOYEE_PORT=8083 
    ports: 
      - "8083:8083" 
    networks: 
      - meeting-network 
    depends_on: 
      - central-server 
    volumes: 
      - ./data:/app/data 
      - ./employees.properties:/app/employees.properties 
 
  david-black-server: 
    image: martin2000002/meeting-employee-server:latest 
    environment: 
      - EMPLOYEE_NAME=David_Black 
      - EMPLOYEE_PORT=8084 
    ports: 
      - "8084:8084" 
    networks: 
      - meeting-network 
    depends_on: 
      - central-server 
    volumes: 
      - ./data:/app/data 
      - ./employees.properties:/app/employees.properties 
 
  martin-montero-server: 
    image: martin2000002/meeting-employee-server:latest 
    environment: 
      - EMPLOYEE_NAME=MARTIN_MONTERO 
      - EMPLOYEE_PORT=8085 
    ports: 
      - "8085:8085" 
    networks: 
      - meeting-network 
    depends_on: 
      - central-server 
    volumes: 
      - ./data:/app/data 
      - ./employees.properties:/app/employees.properties 
 
  client: 
    image: martin2000002/meeting-client:latest 
    networks: 
      - meeting-network 
    depends_on: 
      - central-server 
      - alice-white-server 
      - bob-smith-server 
      - carol-simpson-server 
      - david-black-server 
      - martin-montero-server 
    volumes: 
      - ./data:/app/data 
      - ./employees.properties:/app/employees.properties 
    extra_hosts: 
      - "host.docker.internal:host-gateway" 
 
networks: 
  meeting-network: 
    driver: bridge 
