services:
  central-server:
    build:
      context: .
      dockerfile: DockerfileCentral
    ports:
      - "9090:9090"
    networks:
      - meeting-network
    # Eliminamos el volumen que sobrescribía los archivos compilados

  alice-server:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - EMPLOYEE_NAME=Alice_White
        - EMPLOYEE_PORT=8081
    ports:
      - "8081:8081"
    networks:
      - meeting-network
    depends_on:
      - central-server
    # Eliminamos el volumen que sobrescribía los archivos compilados

  bob-server:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - EMPLOYEE_NAME=Bob_Smith
        - EMPLOYEE_PORT=8082
    ports:
      - "8082:8082"
    networks:
      - meeting-network
    depends_on:
      - central-server
    # Eliminamos el volumen que sobrescribía los archivos compilados

  carol-server:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - EMPLOYEE_NAME=Carol_Simpson
        - EMPLOYEE_PORT=8083
    ports:
      - "8083:8083"
    networks:
      - meeting-network
    depends_on:
      - central-server
    # Eliminamos el volumen que sobrescribía los archivos compilados

  david-server:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - EMPLOYEE_NAME=David_Black
        - EMPLOYEE_PORT=8084
    ports:
      - "8084:8084"
    networks:
      - meeting-network
    depends_on:
      - central-server
    # Eliminamos el volumen que sobrescribía los archivos compilados

  eva-server:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - EMPLOYEE_NAME=Eva_Brown
        - EMPLOYEE_PORT=8085
    ports:
      - "8085:8085"
    networks:
      - meeting-network
    depends_on:
      - central-server
    # Eliminamos el volumen que sobrescribía los archivos compilados

  client:
    build:
      context: .
      dockerfile: DockerfileClient
    networks:
      - meeting-network
    depends_on:
      - central-server
      - alice-server
      - bob-server
      - carol-server
      - david-server
      - eva-server
    volumes:
      # Mantenemos este volumen para poder acceder a los archivos de reuniones
      - ./:/app/data
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  meeting-network:
    driver: bridge